services:
  db:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./data:/usr/local/etc/redis
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
      HOST: 172.21.96.1
    ports:
      - 3000:3000
